// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef SILABS_THREAD_CONFIG
#define SILABS_THREAD_CONFIG




// Top level macros
#define EMBER_AF_DEVICE_NAME "server"


// Generated setup headers that are included automatically
#include "thread-debug-print.h"


// Generated plugin macros

// Use this macro to check if ADC plugin is included
#define EMBER_AF_PLUGIN_ADC

// Use this macro to check if Address Configuration Debug plugin is included
#define EMBER_AF_PLUGIN_ADDRESS_CONFIGURATION_DEBUG

// Use this macro to check if Antenna Stub plugin is included
#define EMBER_AF_PLUGIN_ANTENNA_STUB

// Use this macro to check if Button plugin is included
#define EMBER_AF_PLUGIN_BUTTON

// Use this macro to check if Buzzer plugin is included
#define EMBER_AF_PLUGIN_BUZZER

// Use this macro to check if CLI plugin is included
#define EMBER_AF_PLUGIN_CLI

// Use this macro to check if CoAP CLI plugin is included
#define EMBER_AF_PLUGIN_COAP_CLI

// Use this macro to check if CoAP Dispatch plugin is included
#define EMBER_AF_PLUGIN_COAP_DISPATCH

// Use this macro to check if Radio Coexistence Stub plugin is included
#define EMBER_AF_PLUGIN_COEXISTENCE_STUB

// Use this macro to check if Command Interpreter plugin is included
#define EMBER_AF_PLUGIN_COMMAND_INTERPRETER2

// Use this macro to check if Debug JTAG plugin is included
#define EMBER_AF_PLUGIN_DEBUG_CHANNEL

// Use this macro to check if Debug Print plugin is included
#define EMBER_AF_PLUGIN_DEBUG_PRINT
// User options for plugin Debug Print
#define EMBER_AF_DEBUG_PRINT_USE_PORT

// Use this macro to check if Dynamic Host Configuration Protocol (DHCP) Client plugin is included
#define EMBER_AF_PLUGIN_DHCP_CLIENT

// Use this macro to check if DHCP Library plugin is included
#define EMBER_AF_PLUGIN_DHCP_LIBRARY

// Use this macro to check if Diagnostic plugin is included
#define EMBER_AF_PLUGIN_DIAGNOSTIC

// Use this macro to check if DTLS Authentication Parameters plugin is included
#define EMBER_AF_PLUGIN_DTLS_AUTH_PARAMS
// User options for plugin DTLS Authentication Parameters

// Use this macro to check if Global Address/Prefix Debug plugin is included
#define EMBER_AF_PLUGIN_GLOBAL_ADDRESS_PREFIX_DEBUG

// Use this macro to check if HAL Library plugin is included
#define EMBER_AF_PLUGIN_HAL_LIBRARY

// Use this macro to check if Heartbeat plugin is included
#define EMBER_AF_PLUGIN_HEARTBEAT
// User options for plugin Heartbeat
#define EMBER_AF_PLUGIN_HEARTBEAT_PERIOD_QS 1

// Use this macro to check if ICMP CLI plugin is included
#define EMBER_AF_PLUGIN_ICMP_CLI

// Use this macro to check if ICMP Debug plugin is included
#define EMBER_AF_PLUGIN_ICMP_DEBUG

// Use this macro to check if Idle/Sleep plugin is included
#define EMBER_AF_PLUGIN_IDLE_SLEEP
// User options for plugin Idle/Sleep
#define EMBER_AF_PLUGIN_IDLE_SLEEP_MINIMUM_SLEEP_DURATION_MS 5

// Use this macro to check if LED plugin is included
#define EMBER_AF_PLUGIN_LED

// Use this macro to check if Main plugin is included
#define EMBER_AF_PLUGIN_MAIN

// Use this macro to check if mbed TLS Cryptographic Library plugin is included
#define EMBER_AF_PLUGIN_MBEDTLS_LIBRARY

// Use this macro to check if Manufacturing Library plugin is included
#define EMBER_AF_PLUGIN_MFGLIB_LIBRARY

// Use this macro to check if Network Management CLI plugin is included
#define EMBER_AF_PLUGIN_NETWORK_MANAGEMENT_CLI

// Use this macro to check if RAIL Library plugin is included
#define EMBER_AF_PLUGIN_RAIL_LIBRARY
// User options for plugin RAIL Library
#define EMBER_AF_PLUGIN_RAIL_LIBRARY_RAILPHYDEF 1

// Use this macro to check if Scan Debug plugin is included
#define EMBER_AF_PLUGIN_SCAN_DEBUG

// Use this macro to check if Serial plugin is included
#define EMBER_AF_PLUGIN_SERIAL

// Use this macro to check if Simulated EEPROM version 1 Library plugin is included
#define EMBER_AF_PLUGIN_SIM_EEPROM1
// User options for plugin Simulated EEPROM version 1 Library

// Use this macro to check if Stateless Address Autoconfiguration (SLAAC) Client plugin is included
#define EMBER_AF_PLUGIN_SLAAC_CLIENT

// Use this macro to check if Thread Stack Library with Silicon Labs TLS support plugin is included
#define EMBER_AF_PLUGIN_THREAD_STACK

// Use this macro to check if UDP CLI plugin is included
#define EMBER_AF_PLUGIN_UDP_CLI

// Use this macro to check if Version Debug plugin is included
#define EMBER_AF_PLUGIN_VERSION_DEBUG


// Generated API headers

// API adc-cortexm3 from ADC plugin
#define EMBER_AF_API_ADC_CORTEXM3 "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/adc/adc-cortexm3.h"

// API adc from ADC plugin
#define EMBER_AF_API_ADC "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/adc/adc.h"

// API antenna from Antenna Stub plugin
#define EMBER_AF_API_ANTENNA "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/antenna/antenna.h"

// API button from Button plugin
#define EMBER_AF_API_BUTTON "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/button.h"

// API buzzer from Buzzer plugin
#define EMBER_AF_API_BUZZER "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/buzzer/buzzer.h"

// API coap-dispatch from CoAP Dispatch plugin
#define EMBER_AF_API_COAP_DISPATCH "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/coap-dispatch/coap-dispatch.h"

// API coexistence from Radio Coexistence Stub plugin
#define EMBER_AF_API_COEXISTENCE "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154/coexistence-802154.h"

// API command-interpreter2 from Command Interpreter plugin
#define EMBER_AF_API_COMMAND_INTERPRETER2 "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/util/serial/command-interpreter2.h"

// API debug-print from Debug Print plugin
#define EMBER_AF_API_DEBUG_PRINT "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/app/thread/plugin/debug-print/debug-print.h"

// API diagnostic-cortexm3 from Diagnostic plugin
#define EMBER_AF_API_DIAGNOSTIC_CORTEXM3 "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/cortexm3/diagnostic.h"

// API diagnostic from Diagnostic plugin
#define EMBER_AF_API_DIAGNOSTIC "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/diagnostic.h"

// API crc from HAL Library plugin
#define EMBER_AF_API_CRC "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/crc.h"

// API endian from HAL Library plugin
#define EMBER_AF_API_ENDIAN "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/endian.h"

// API hal from HAL Library plugin
#define EMBER_AF_API_HAL "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/hal.h"

// API random from HAL Library plugin
#define EMBER_AF_API_RANDOM "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/random.h"

// API system-timer from HAL Library plugin
#define EMBER_AF_API_SYSTEM_TIMER "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/system-timer.h"

// API token-cortexm3 from HAL Library plugin
#define EMBER_AF_API_TOKEN_CORTEXM3 "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/cortexm3/token.h"

// API token from HAL Library plugin
#define EMBER_AF_API_TOKEN "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/token.h"

// API led from LED plugin
#define EMBER_AF_API_LED "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/micro/led.h"

// API mfglib from Manufacturing Library plugin
#define EMBER_AF_API_MFGLIB "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/mfglib.h"

// API rail-library from RAIL Library plugin
#define EMBER_AF_API_RAIL_LIBRARY "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/radio/rail_lib/common/rail.h"

// API serial from Serial plugin
#define EMBER_AF_API_SERIAL "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/serial/serial.h"

// API sim-eeprom from Simulated EEPROM version 1 Library plugin
#define EMBER_AF_API_SIM_EEPROM "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/platform/base/hal/plugin/sim-eeprom/sim-eeprom.h"

// API buffer-management from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_BUFFER_MANAGEMENT "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/framework/buffer-management.h"

// API buffer-queue from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_BUFFER_QUEUE "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/framework/buffer-queue.h"

// API child from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_CHILD "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/child.h"

// API coap-diagnostic from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_COAP_DIAGNOSTIC "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/network-diagnostics.h"

// API coap from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_COAP "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/coap.h"

// API event-queue from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_EVENT_QUEUE "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/framework/event-queue.h"

// API event from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_EVENT "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/event.h"

// API icmp from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_ICMP "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/icmp.h"

// API network-diagnostics from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_NETWORK_DIAGNOSTICS "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/network-diagnostics.h"

// API network-management from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_NETWORK_MANAGEMENT "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/network-management.h"

// API stack-info from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_STACK_INFO "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/stack-info.h"

// API stack from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_STACK "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/ember.h"

// API tcp from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_TCP "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/tcp.h"

// API udp-peer from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_UDP_PEER "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/udp-peer.h"

// API udp from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_UDP "../../../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.6/protocol/thread/stack/include/udp.h"


// Coap Dispatch macros
#ifdef EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH
#undef EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH
#endif
#define EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH 13


// Custom macros
#ifdef EMBER_AF_RADIO
#undef EMBER_AF_RADIO
#endif
#define EMBER_AF_RADIO EFR32

#ifdef EMBER_AF_RADIO_FULL
#undef EMBER_AF_RADIO_FULL
#endif
#define EMBER_AF_RADIO_FULL EFR32MG13P632F512GM48

#ifdef EMBER_AF_RADIO_FAMILY
#undef EMBER_AF_RADIO_FAMILY
#endif
#define EMBER_AF_RADIO_FAMILY M

#ifdef EMBER_AF_RADIO_SERIES
#undef EMBER_AF_RADIO_SERIES
#endif
#define EMBER_AF_RADIO_SERIES 1

#ifdef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#undef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_RADIO_DEVICE_CONFIGURATION 3

#ifdef EMBER_AF_RADIO_PERFORMANCE
#undef EMBER_AF_RADIO_PERFORMANCE
#endif
#define EMBER_AF_RADIO_PERFORMANCE P

#ifdef EMBER_AF_RADIO_RADIO
#undef EMBER_AF_RADIO_RADIO
#endif
#define EMBER_AF_RADIO_RADIO 632

#ifdef EMBER_AF_RADIO_FLASH
#undef EMBER_AF_RADIO_FLASH
#endif
#define EMBER_AF_RADIO_FLASH 512K

#ifdef EMBER_AF_RADIO_TEMP
#undef EMBER_AF_RADIO_TEMP
#endif
#define EMBER_AF_RADIO_TEMP G

#ifdef EMBER_AF_RADIO_PACKAGE
#undef EMBER_AF_RADIO_PACKAGE
#endif
#define EMBER_AF_RADIO_PACKAGE M

#ifdef EMBER_AF_RADIO_PINS
#undef EMBER_AF_RADIO_PINS
#endif
#define EMBER_AF_RADIO_PINS 48

#ifdef EMBER_AF_RADIO_MODULE
#undef EMBER_AF_RADIO_MODULE
#endif
#define EMBER_AF_RADIO_MODULE XX

#ifdef EMBER_AF_MCU
#undef EMBER_AF_MCU
#endif
#define EMBER_AF_MCU EFR32

#ifdef EMBER_AF_MCU_FULL
#undef EMBER_AF_MCU_FULL
#endif
#define EMBER_AF_MCU_FULL EFR32MG13P632F512GM48

#ifdef EMBER_AF_MCU_FAMILY
#undef EMBER_AF_MCU_FAMILY
#endif
#define EMBER_AF_MCU_FAMILY M

#ifdef EMBER_AF_MCU_SERIES
#undef EMBER_AF_MCU_SERIES
#endif
#define EMBER_AF_MCU_SERIES 1

#ifdef EMBER_AF_MCU_DEVICE_CONFIGURATION
#undef EMBER_AF_MCU_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_MCU_DEVICE_CONFIGURATION 3

#ifdef EMBER_AF_MCU_PERFORMANCE
#undef EMBER_AF_MCU_PERFORMANCE
#endif
#define EMBER_AF_MCU_PERFORMANCE P

#ifdef EMBER_AF_MCU_RADIO
#undef EMBER_AF_MCU_RADIO
#endif
#define EMBER_AF_MCU_RADIO 632

#ifdef EMBER_AF_MCU_FLASH
#undef EMBER_AF_MCU_FLASH
#endif
#define EMBER_AF_MCU_FLASH 512K

#ifdef EMBER_AF_MCU_TEMP
#undef EMBER_AF_MCU_TEMP
#endif
#define EMBER_AF_MCU_TEMP G

#ifdef EMBER_AF_MCU_PACKAGE
#undef EMBER_AF_MCU_PACKAGE
#endif
#define EMBER_AF_MCU_PACKAGE M

#ifdef EMBER_AF_MCU_PINS
#undef EMBER_AF_MCU_PINS
#endif
#define EMBER_AF_MCU_PINS 48

#ifdef EMBER_AF_MCU_MODULE
#undef EMBER_AF_MCU_MODULE
#endif
#define EMBER_AF_MCU_MODULE XX

#ifdef EMBER_AF_BOARD_TYPE
#undef EMBER_AF_BOARD_TYPE
#endif
#define EMBER_AF_BOARD_TYPE BRD4159A



#endif // SILABS_THREAD_CONFIG
