// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include EMBER_AF_API_STACK

// OkToSleep function declarations.
bool emberAfPluginIdleSleepOkToSleepCallback(uint32_t durationMs);  // Plugin: idle-sleep

bool emberAfOkToSleep(uint32_t durationMs)
{
  return emberAfPluginIdleSleepOkToSleepCallback(durationMs);  // Plugin: idle-sleep
}

// WakeUp function declarations.
void emberAfPluginIdleSleepWakeUpCallback(uint32_t durationMs);  // Plugin: idle-sleep

void emberAfPluginIdleSleepWakeUp(uint32_t durationMs)
{
  emberAfPluginIdleSleepWakeUpCallback(durationMs);  // Plugin: idle-sleep
}

// OkToIdle function declarations.
bool emberAfPluginIdleSleepOkToIdleCallback(uint32_t durationMs);  // Plugin: idle-sleep

bool emberAfOkToIdle(uint32_t durationMs)
{
  return emberAfPluginIdleSleepOkToIdleCallback(durationMs);  // Plugin: idle-sleep
}

// Active function declarations.
void emberAfPluginIdleSleepActiveCallback(uint32_t durationMs);  // Plugin: idle-sleep

void emberAfPluginIdleSleepActive(uint32_t durationMs)
{
  emberAfPluginIdleSleepActiveCallback(durationMs);  // Plugin: idle-sleep
}

// Main function declarations.
void emberAfMainCallback(MAIN_FUNCTION_PARAMETERS);  // Plugin: main

void emAfMain(MAIN_FUNCTION_PARAMETERS)
{
  emberAfMainCallback(MAIN_FUNCTION_ARGUMENTS);  // Plugin: main
}

// Init function declarations.
void emberCommandReaderInit(void);  // Plugin: command-interpreter2
void emberAfInitCallback(void);  // Plugin: main

void emAfInit(void)
{
  emberCommandReaderInit();  // Plugin: command-interpreter2
  emberAfInitCallback();  // Plugin: main
}

// Tick function declarations.
void emberAfPluginCliTickCallback(void);  // Plugin: cli
void emberAfPluginHeartbeatTickCallback(void);  // Plugin: heartbeat
void emberAfPluginIdleSleepTickCallback(void);  // Plugin: idle-sleep
void emberTick(void);  // Plugin: main
void emberAfTickCallback(void);  // Plugin: main
void emberSerialBufferTick(void);  // Plugin: serial

void emAfTick(void)
{
  emberAfPluginCliTickCallback();  // Plugin: cli
  emberAfPluginHeartbeatTickCallback();  // Plugin: heartbeat
  emberAfPluginIdleSleepTickCallback();  // Plugin: idle-sleep
  emberTick();  // Plugin: main
  emberAfTickCallback();  // Plugin: main
  emberSerialBufferTick();  // Plugin: serial
}

// MarkApplicationBuffers function declarations.
void emberAfMarkApplicationBuffersCallback(void);  // Plugin: main

void emAfMarkApplicationBuffers(void)
{
  emberAfMarkApplicationBuffersCallback();  // Plugin: main
}

// NetworkStatus function declarations.
void emberAfNetworkStatusCallback(EmberNetworkStatus newNetworkStatus, EmberNetworkStatus oldNetworkStatus, EmberJoinFailureReason reason);  // Plugin: main

void emberNetworkStatusHandler(EmberNetworkStatus newNetworkStatus, EmberNetworkStatus oldNetworkStatus, EmberJoinFailureReason reason)
{
  emberAfNetworkStatusCallback(newNetworkStatus, oldNetworkStatus, reason);  // Plugin: main
}
